PS1='\[\033[01;32m\]\u\[\033[01;33m\]@\[\033[01;32m\]\h: \[\033[01;33m\]\w \[\033[01;35m\]\$ \[\033[00m\]'
alias ls="ls --color=auto"

cd ~/

if [ -d ~/.bashrc.d ]; then
    for bashrc_script in $(find ~/.bashrc.d -type f); do
        source "$bashrc_script"
    done
fi
